import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ModalProvider } from "@/components/providers/modal.provider";
import { QueryProvider } from "@/components/providers/query-provider";

const kanit = Kanit({ weight: ["300", "400", "500", "600", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <QueryProvider>
                <html lang="en">
                    <body className={kanit.className}>{children}</body>
                    <Toaster />
                    <ModalProvider />
                </html>
            </QueryProvider>
        </ClerkProvider>
    );
}
